export const APP_ROUTES = {
  dashboard: '/app',
  offers: '/app/offers',
  map: '/app/map',
  requests: '/app/requests',
  matches: '/app/matches',
  notifications: '/app/notifications',
  users: '/app/users',
  teams: '/app/teams',
  chat: '/app/chat',
  reports: '/app/reports',
  auditLogs: '/app/audit-logs',
  websiteAdmin: '/app/website',
  settingsAdmin: '/app/settings/flags',
  commissionCalculator: '/app/tools/commission',
  myPoints: '/app/my-points',
  rewards: '/app/rewards',
  leaderboard: '/app/leaderboard',
  offices: '/app/offices',
  registrations: '/app/registrations',
  joinApplications: '/app/join-applications',
  landComparables: '/app/lands/comparables',
  feasibilityTool: '/app/tools/feasibility',
  search: '/app/search',
  subscriptions: '/app/subscription',
  profile: '/app/profile',
  noAccess: '/app/no-access',
};

export const PAGE_REDIRECTS = [
  { page: 'dashboard', to: APP_ROUTES.dashboard },
  { page: 'offers', to: APP_ROUTES.offers },
  { page: 'map', to: APP_ROUTES.map },
  { page: 'offers.create', to: APP_ROUTES.offers },
  { page: 'requests', to: APP_ROUTES.requests },
  { page: 'requests.create', to: APP_ROUTES.requests },
  { page: 'matches', to: APP_ROUTES.matches },
  { page: 'notifications', to: APP_ROUTES.notifications },
  { page: 'users', to: APP_ROUTES.users },
  { page: 'teams', to: APP_ROUTES.teams },
  { page: 'conversations', to: APP_ROUTES.chat },
  { page: 'reports', to: APP_ROUTES.reports },
  { page: 'auditLogs', to: APP_ROUTES.auditLogs },
  { page: 'websiteAdmin', to: APP_ROUTES.websiteAdmin },
  { page: 'settingsAdmin', to: APP_ROUTES.settingsAdmin },
  { page: 'commissionCalculator', to: APP_ROUTES.commissionCalculator },
  { page: 'myPoints', to: APP_ROUTES.myPoints },
  { page: 'rewards', to: APP_ROUTES.rewards },
  { page: 'leaderboard', to: APP_ROUTES.leaderboard },
  { page: 'offices', to: APP_ROUTES.offices },
  { page: 'registrations', to: APP_ROUTES.registrations },
  { page: 'joinApplications', to: APP_ROUTES.joinApplications },
  { page: 'landComparables', to: APP_ROUTES.landComparables },
  { page: 'feasibilityTool', to: APP_ROUTES.feasibilityTool },
  { page: 'search', to: APP_ROUTES.search },
  { page: 'subscriptions', to: APP_ROUTES.subscriptions },
];

/** Old paths without /app prefix — redirect for bookmarks and stale links */
export const LEGACY_APP_REDIRECTS = [
  { from: '/offers', to: APP_ROUTES.offers },
  { from: '/requests', to: APP_ROUTES.requests },
  { from: '/matches', to: APP_ROUTES.matches },
  { from: '/teams', to: APP_ROUTES.teams },
  { from: '/users', to: APP_ROUTES.users },
  { from: '/notifications', to: APP_ROUTES.notifications },
  { from: '/chat', to: APP_ROUTES.chat },
  { from: '/map', to: APP_ROUTES.map },
];
