import { SIDEBAR_PAGE_FLAG_MAP } from "../../config/featureFlagCatalog";
import { UI_LABELS_AR } from "../../constants/uiLabels.ar";
import {
  Bell,
  Buildings,
  Calculator,
  ChartPieSlice,
  ChatCircle,
  CreditCard,
  Crown,
  FileArrowDown,
  Gear,
  Gift,
  Globe,
  Handshake,
  MagnifyingGlass,
  MapTrifold,
  Medal,
  Mountains,
  Scroll,
  Storefront,
  SquaresFour,
  UserPlus,
  Users,
  UsersThree,
} from "phosphor-react";

export const SIDEBAR_VISIBILITY = {
  ALWAYS: "always",
  ADMIN: "admin",
  ADMIN_MANAGER_EMPLOYEE: "admin_manager_employee",
  ADMIN_MANAGER_EMPLOYEE_BROKER: "admin_manager_employee_broker",
  ADMIN_MANAGER_DATA_ENTRY: "admin_manager_data_entry",
  ADMIN_BROKER: "admin_broker",
  ADMIN_MANAGER_BROKER: "admin_manager_broker",
  ADMIN_MANAGER: "admin_manager",
  ADMIN_MANAGER_OFFICE_MEMBER: "admin_manager_office_member",
  ADMIN_MANAGER_EMPLOYEE_DATA_ENTRY: "admin_manager_employee_data_entry",
  ADMIN_MANAGER_EMPLOYEE_BROKER_DATA_ENTRY: "admin_manager_employee_broker_data_entry",
  AUDIT: "audit",
  REPORTS: "reports",
  WEBSITE_CMS: "website_cms",
  SETTINGS_ADMIN: "settings_admin",
};

export const SIDEBAR_NAV_ITEMS = [
  {
    to: "/app",
    icon: SquaresFour,
    label: "لوحة التحكم",
    visibility: SIDEBAR_VISIBILITY.ALWAYS,
    page: "dashboard",
  },
  {
    to: "/app/offers",
    icon: Buildings,
    label: "العروض العقارية",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_EMPLOYEE_BROKER_DATA_ENTRY,
    page: "offers",
  },
  {
    to: "/app/map",
    icon: MapTrifold,
    label: "خريطة العقارات",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_EMPLOYEE_BROKER,
    page: "map",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.map,
  },
  {
    to: "/app/tools/commission",
    icon: Calculator,
    label: "حاسبة السعي",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_BROKER,
    page: "commissionCalculator",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.commissionCalculator,
  },
  {
    to: "/app/tools/feasibility",
    icon: ChartPieSlice,
    label: "دراسة الجدوى",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_BROKER,
    page: "feasibilityTool",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.feasibilityTool,
  },
  {
    to: "/app/lands/comparables",
    icon: Mountains,
    label: "صفقات المقارنة",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER,
    page: "landComparables",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.landComparables,
  },
  {
    to: "/app/my-points",
    icon: Medal,
    label: "نقاطي",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_BROKER,
    page: "myPoints",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.myPoints,
  },
  {
    to: "/app/rewards",
    icon: Gift,
    label: "\u0627\u0644\u0645\u0643\u0627\u0641\u0622\u062a",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_BROKER,
    page: "rewards",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.rewards,
  },
  {
    to: "/app/leaderboard",
    icon: Crown,
    label: "المتصدرين",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_BROKER,
    page: "leaderboard",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.leaderboard,
  },
  {
    to: "/app/search",
    icon: MagnifyingGlass,
    label: "البحث المتقدم",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_EMPLOYEE_BROKER,
    page: "search",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.search,
  },
  {
    to: "/app/subscription",
    icon: CreditCard,
    label: "الاشتراك",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_BROKER,
    page: "subscriptions",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.subscriptions,
  },
  {
    to: "/app/requests",
    icon: MagnifyingGlass,
    label: "طلبات العملاء",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_EMPLOYEE_BROKER_DATA_ENTRY,
    page: "requests",
  },
  {
    to: "/app/matches",
    icon: Handshake,
    label: "التطابقات الذكية",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_BROKER,
    page: "matches",
  },
  {
    to: "/app/notifications",
    icon: Bell,
    label: "التنبيهات",
    visibility: SIDEBAR_VISIBILITY.ALWAYS,
    page: "notifications",
  },
  {
    to: "/app/registrations",
    icon: UserPlus,
    label: "طلبات التسجيل",
    visibility: SIDEBAR_VISIBILITY.ADMIN,
    page: "registrations",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.registrations,
  },
  {
    to: "/app/join-applications",
    icon: UsersThree,
    label: "طلبات الانضمام",
    visibility: SIDEBAR_VISIBILITY.ADMIN,
    page: "joinApplications",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.joinApplications,
  },
  {
    to: "/app/users",
    icon: Users,
    label: "المستخدمين",
    visibility: SIDEBAR_VISIBILITY.ADMIN,
    page: "users",
  },
  {
    to: "/app/audit-logs",
    icon: Scroll,
    label: "سجلات التدقيق",
    visibility: SIDEBAR_VISIBILITY.AUDIT,
    page: "auditLogs",
  },
  {
    to: "/app/reports",
    icon: FileArrowDown,
    label: "التقارير",
    visibility: SIDEBAR_VISIBILITY.REPORTS,
    page: "reports",
  },
  {
    to: "/app/website",
    icon: Globe,
    label: UI_LABELS_AR.websiteCms,
    visibility: SIDEBAR_VISIBILITY.WEBSITE_CMS,
    page: "websiteAdmin",
  },
  {
    to: "/app/settings/flags",
    icon: Gear,
    label: "إعدادات النظام",
    visibility: SIDEBAR_VISIBILITY.SETTINGS_ADMIN,
    page: "settingsAdmin",
  },
  {
    to: "/app/offices",
    icon: Storefront,
    label: "المكاتب العقارية",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_OFFICE_MEMBER,
    page: "offices",
    requiredFlag: SIDEBAR_PAGE_FLAG_MAP.offices,
  },
  {
    to: "/app/teams",
    icon: UsersThree,
    label: "إدارة الفرق",
    visibility: SIDEBAR_VISIBILITY.ADMIN_MANAGER_EMPLOYEE_DATA_ENTRY,
    page: "teams",
  },
  {
    to: "/app/chat",
    icon: ChatCircle,
    label: "المحادثات",
    visibility: SIDEBAR_VISIBILITY.ALWAYS,
    page: "conversations",
  },
];
