export const projects = [
    {
        id: 1,
        title: "فيلا فاخرة في الرياض",
        type: "property",
        price: "2,500,000 ريال",
        location: "الرياض",
        image: "images/feature1.jpg",
        beds: 4,
        baths: 3,
    },
    {
        id: 2,
        title: "أرض استثمارية مميزة",
        type: "land",
        price: "1,200,000 ريال",
        location: "جدة",
        image: "images/feature2.jpg",
    },
    {
        id: 3,
        title: "مكتب تجاري حديث",
        type: "office",
        price: "850,000 ريال",
        location: "الدمام",
        image: "images/feature3.jpg",
    },
    {
        id: 4,
        title: "شقة سكنية راقية",
        type: "property",
        price: "900,000 ريال",
        location: "الرياض",
        image: "images/feature1.jpg",
        beds: 3,
        baths: 2,
    },
    {
        id: 5,
        title: "فيلا عصرية بتصميم حديث",
        type: "property",
        price: "3,200,000 ريال",
        location: "الرياض",
        image: "images/feature2.jpg",
        beds: 5,
        baths: 4,
    },
    {
        id: 6,
        title: "أرض سكنية في موقع مميز",
        type: "land",
        price: "750,000 ريال",
        location: "مكة",
        image: "images/feature3.jpg",
    },
    {
        id: 7,
        title: "مكتب إداري فاخر",
        type: "office",
        price: "1,100,000 ريال",
        location: "جدة",
        image: "images/feature1.jpg",
    },
    {
        id: 8,
        title: "شقة بإطلالة رائعة",
        type: "property",
        price: "1,300,000 ريال",
        location: "الدمام",
        image: "images/feature2.jpg",
        beds: 3,
        baths: 2,
    },
    {
        id: 9,
        title: "فيلا مستقلة بحديقة",
        type: "property",
        price: "2,800,000 ريال",
        location: "الخبر",
        image: "images/feature3.jpg",
        beds: 4,
        baths: 3,
    },
    {
        id: 10,
        title: "أرض تجارية على شارع رئيسي",
        type: "land",
        price: "1,900,000 ريال",
        location: "الرياض",
        image: "images/feature1.jpg",
    },
    {
        id: 11,
        title: "مكتب أعمال حديث",
        type: "office",
        price: "950,000 ريال",
        location: "الرياض",
        image: "images/feature2.jpg",
    },
    {
        id: 12,
        title: "شقة فاخرة في برج سكني",
        type: "property",
        price: "1,700,000 ريال",
        location: "جدة",
        image: "images/feature3.jpg",
        beds: 3,
        baths: 2,
    },
];